### ISSUE TITLE
Random crashes in com.aghajari.rlottie.DispatchQueuePool

### ISSUE THREAD

**Issue by dstukalov** [Aghajari/AXrLottie#13]
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.aghajari.rlottie.DispatchQueuePool$2$1.run(DispatchQueuePool.java:102)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

using with Glide

I believe number of AXrLottieDrawable shown on screen highly affects the probability of the crash

**Comment by Aghajari** [comment]
Hi, 
This only happen when you are using Glide?

**Comment by dstukalov** [comment]
Yes, it happens when using with Glide

**Comment by Aghajari** [comment]
Hey, try v1.2.0
