### ISSUE TITLE
could not load needed library 'librlottie.so' for 'libjlottie.so' (load_library[1095]: Library 'librlottie.so' not found)

### ISSUE THREAD

**Issue by hysapp** [Aghajari/AXrLottie#15]
I got this error when I debugged the app on LG Optimus L9:
`  java.lang.ExceptionInInitializerError
        at com.hyapp.a18chat.bl.App.onCreate(App.java:26)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1002)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4252)
        at android.app.ActivityThread.access$1300(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4849)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1893]:   141 could not load needed library 'librlottie.so' for 'libjlottie.so' (load_library[1095]: Library 'librlottie.so' not found)
        at java.lang.Runtime.loadLibrary(Runtime.java:370)
        at java.lang.System.loadLibrary(System.java:538)
        at com.aghajari.rlottie.AXrLottie.<clinit>(AXrLottie.java:48)
        at com.hyapp.a18chat.bl.App.onCreate(App.java:26) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1002) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4252) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4849) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562) 
        at dalvik.system.NativeStart.main(Native Method) `

This error occurred in this line of code:
       `AXrLottie.init(this);`

**Comment by Aghajari** [comment]
Hi, 
Does it only happen in debug mode?

**Comment by hysapp** [comment]
No, it also happens in release mode and the app crashes.

**Comment by Aghajari** [comment]
Must be because of the android version of the phone,
https://www.lg.com/us/cell-phones/lg-P769-optimus-l9

This is a really old phone, i will test it on a simulator and share the result with you soon.

**Comment by hysapp** [comment]
Okay, but I tested the Telegram app on that phone and the animations worked fine.

**Comment by hysapp** [comment]
Okay, but I tested the Telegram app on that phone and the animations worked fine.
It's really a good library. It is 10 times faster than [Lottie](https://github.com/airbnb/lottie-android). I believe that if you provide a stable version, it can become very popular and practical.

**Comment by hysapp** [comment]
Are you developing a new version?

**Comment by Aghajari** [comment]
Hi @hysapp ,
Check out v1.3.0
Hopefully it's going to work like a charm.
I look forward to hearing from you soon.
