### ISSUE TITLE
LeakedClosableViolation

### ISSUE THREAD

**Issue by Dolfik1** [Aghajari/AXrLottie#19]
I got this error on AXrLottie 1.1.0 but I have not found a fix for this error in any release after 1.1.0.

```
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1924)

        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:303)

        at java.io.FileOutputStream.finalize(FileOutputStream.java:492)

        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)

        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)

        at java.lang.Daemons$Daemon.run(Daemons.java:139)

        at java.lang.Thread.run(Thread.java:923)

     Caused by: java.lang.Throwable: Explicit termination method 'close' not called

        at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:259)

        at dalvik.system.CloseGuard.open(CloseGuard.java:230)

        at java.io.FileOutputStream.<init>(FileOutputStream.java:253)

        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)

        at com.aghajari.rlottie.extension.GZipFileExtension.toFile(GZipFileExtension.java:58)

        at com.aghajari.rlottie.extension.GZipFileExtension.toFile(GZipFileExtension.java:78)

        at com.aghajari.rlottie.extension.AXrFileExtension.toFile(AXrFileExtension.java:54)

        at com.aghajari.rlottie.decoder.AXrFileReader.read(AXrFileReader.java:107)

        at com.aghajari.rlottie.decoder.AXrFileReader.fromAssets(AXrFileReader.java:83)

        at com.aghajari.rlottie.AXrLottieDrawable.fromAssets(AXrLottieDrawable.java:1272)

        at com.aghajari.rlottie.AXrLottieDrawable.fromAssets(AXrLottieDrawable.java:1268)

        at com.aghajari.rlottie.AXrLottie$Loader.createFromAssets(AXrLottie.java:245)
```

**Comment by Aghajari** [comment]
Fixed on v1.4.0
